### ISSUE TITLE
Exclude VCS directories by default

### ISSUE THREAD

**Issue by ianlewis** [ianlewis/todos#70]
e.g. `.git`, `.hg`, `.svn` etc.

**Comment by ianlewis** [comment]
This panic occurs when scanning `.git` directories.
```
panic: decoding charset: IBM424_ltr: ianaindex: invalid encoding name

goroutine 1 [running]:
github.com/ianlewis/todos/internal/scanner.FromBytes({0xc012038d90, 0x68}, {0xc012030c00, 0xe6, 0x200})
        /usr/local/google/home/ianlewis/src/todos/internal/scanner/scanner.go:108 +0x733
github.com/ianlewis/todos/internal/scanner.FromFile(0xc000b048b0)
        /usr/local/google/home/ianlewis/src/todos/internal/scanner/scanner.go:81 +0xf3
github.com/ianlewis/todos/internal/walker.(*TODOWalker).scanFile(0xc00087db18, 0xc000b048b0)
        /usr/local/google/home/ianlewis/src/todos/internal/walker/walker.go:234 +0x2a
github.com/ianlewis/todos/internal/walker.(*TODOWalker).processFile(0xc00087db18, {0xc011c7b900, 0x36}, {0xc012038d90?, 0x4c8e2f?}, 0x9c4d40?)
        /usr/local/google/home/ianlewis/src/todos/internal/walker/walker.go:230 +0x74
github.com/ianlewis/todos/internal/walker.(*TODOWalker).walkFunc(0xc00087db18, {0xc011c7b900, 0x36}, {0x6c30b8, 0xc011c3a940}, {0x0?, 0x0?})
        /usr/local/google/home/ianlewis/src/todos/internal/walker/walker.go:183 +0x3d3
io/fs.walkDir({0x6c2100, 0xc0002719c0}, {0xc011c7b900, 0x36}, {0x6c30b8, 0xc011c3a940}, 0xc00087da28)
        /usr/local/google/home/ianlewis/opt/go/src/io/fs/walk.go:73 +0x78
io/fs.walkDir({0x6c2100, 0xc0002719c0}, {0xc011c36440, 0xf}, {0x6c30b8, 0xc000beaf80}, 0xc00087da28)
        /usr/local/google/home/ianlewis/opt/go/src/io/fs/walk.go:95 +0x2e6
io/fs.walkDir({0x6c2100, 0xc0002719c0}, {0xc001a212e0, 0xc}, {0x6c30b8, 0xc00020a3c0}, 0xc00087da28)
        /usr/local/google/home/ianlewis/opt/go/src/io/fs/walk.go:95 +0x2e6
io/fs.walkDir({0x6c2100, 0xc0002719c0}, {0xc00001aeb8, 0x4}, {0x6c30b8, 0xc000031f40}, 0xc00087da28)
        /usr/local/google/home/ianlewis/opt/go/src/io/fs/walk.go:95 +0x2e6
io/fs.walkDir({0x6c2100, 0xc0002719c0}, {0x6bf578, 0x1}, {0x6c3080, 0xc0002719d0}, 0xc00087da28)
        /usr/local/google/home/ianlewis/opt/go/src/io/fs/walk.go:95 +0x2e6
io/fs.WalkDir({0x6c2100, 0xc0002719c0}, {0x6bf578, 0x1}, 0xc0000a7a28)
        /usr/local/google/home/ianlewis/opt/go/src/io/fs/walk.go:122 +0xde
github.com/ianlewis/todos/internal/walker.(*TODOWalker).walkDir(...)
        /usr/local/google/home/ianlewis/src/todos/internal/walker/walker.go:134
github.com/ianlewis/todos/internal/walker.(*TODOWalker).Walk(0xc00087db18)
        /usr/local/google/home/ianlewis/src/todos/internal/walker/walker.go:117 +0x1a5
main.newTODOsApp.func1(0xc000031740)
        /usr/local/google/home/ianlewis/src/todos/internal/cmd/todos/app.go:107 +0x13a
github.com/urfave/cli/v2.(*Command).Run(0xc0002691e0, 0xc000031740, {0xc000016040, 0x2, 0x2})
        /usr/local/google/home/ianlewis/go/pkg/mod/github.com/urfave/cli/v2@v2.25.6/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*App).RunContext(0xc0002fc000, {0x6c2e88?, 0xc00001a0c8}, {0xc000016040, 0x2, 0x2})
        /usr/local/google/home/ianlewis/go/pkg/mod/github.com/urfave/cli/v2@v2.25.6/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
        /usr/local/google/home/ianlewis/go/pkg/mod/github.com/urfave/cli/v2@v2.25.6/app.go:309
main.main()
        /usr/local/google/home/ianlewis/src/todos/internal/cmd/todos/main.go:22 +0x45
exit status 2
```
